name: TonalCreamAssistant
description: the system which helps people to choose the right color tone for them using photos.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2
  file_picker: ^4.1.3
  dio: ^4.0.1
  animated_check: ^1.0.5
  bordered_text: ^2.0.0
  camera: 0.9.4+3
  responsive_framework: ^0.1.5
  flutter_screenutil: ^5.0.0+2
  back_button_interceptor: ^5.0.2
  json_annotation: ^4.3.0
  flutter_logs: ^2.1.4
  sentry_flutter: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  json_serializable: ^6.0.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/splash_screen.png
