name: Build All images

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build database
        id: db
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend/db
          push: false
          tags: tnlink/db:latest
      -
        name: Build admin panel
        id: admin
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend/services/admin_panel
          push: false
          tags: tnlink/admin-panel:latest
      -
        name: Build vendor
        id: vendor
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend/services/vendor
          push: false
          tags: tnlink/vendor:latest
      -
        name: Build cv
        id: cv
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend/services/cv
          push: false
          tags: tnlink/cv:latest
      -
        name: Update PR
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Database build ðŸ“š \`${{ steps.db.outcome }}\`
            #### Admin panel build ðŸ’» \`${{ steps.admin.outcome }}\`
            #### Vendor build ðŸ’³ \`${{ steps.vendor.outcome }}\`
            #### CV build ðŸ“¸ \`${{ steps.cv.outcome }}\`

            *Pusher: @${{ github.actor }}, Action:  \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      -
        name: Fail job in case any steps before failed
        if: ${{ failure() }}
        run: exit 1