name: Build All images

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build database
        id: db
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend/db
          push: false
          tags: tnlinc/db:latest
      -
        name: Build nginx
        id: nginx
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/nginx
          push: false
          tags: tnlinc/nginx:latest
      -
        name: Update PR
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Database build ðŸ“š \`${{ steps.db.outcome }}\`
            #### Nginx build ðŸ§­ \`${{ steps.nginx.outcome }}\`

            *Pusher: @${{ github.actor }}, Action:  \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      -
        name: Fail job in case any steps before failed
        if: steps.db.outcome != 'success' || steps.vendor.outcome != 'success' || steps.admin.outcome != 'success' || steps.cv.outcome != 'success' || steps.nginx.outcome != 'success'
        run: exit 1