name: Create tag | Upload all images
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build database
        id: db
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend/db
          push: true
          tags: |
            tnlinc/db:${{ steps.tag_version.outputs.new_tag }}
            tnlinc/db:latest
      -
        name: Build nginx
        id: nginx
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./infrastructure/nginx
          push: true
          tags: |
            tnlinc/nginx:${{ steps.tag_version.outputs.new_tag }}
            tnlinc/nginx:latest